services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=shimokita-vintage-junction'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql
